"use client";

import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import { SessionProvider, SessionProviderProps } from "next-auth/react";

const roboto = Roboto_Flex({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: SessionProviderProps;
}) {
  return (
    <html lang="pt-br">
      <SessionProvider session={session}>
        <body className={roboto.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
