"use client";

import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto_Flex({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export interface AuthContextProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: AuthContextProps) {
  return (
    <SessionProvider>
      <html lang="pt-br">
        <body className={roboto.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
