import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

interface childrenProps {
  children: React.ReactNode;
}

export default function WatchLayout({ children }: childrenProps) {
  return <div>{children}</div>;
}
